name: firebase_auth_bug
description: Firebase Auth Bug Example
publish_to: none
version: 0.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true